name = "vie"
version = "0.1.0"
defaultTargets = ["vie"]
testDriver = "test"

[[lean_lib]]
name = "ViE"

[[lean_lib]]
name = "Test"

[[lean_exe]]
name = "vie"
root = "Main"

[[lean_exe]]
name = "test"
root = "Test"

[[lean_exe]]
name = "bench"
root = "Test.Benchmark"

[[lean_exe]]
name = "tree-stats"
root = "Test.TreeStats"
